spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacancy
    username: postgres
    password: gmb1998
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true